version: 2

models:
  - name: dim_zones
  - name: fact_trips
  - name: dm_monthly_zone_revenue
    columns:
      - name: revenue_monthly_total_amount
        tests:
            - not_null:
                severity: error
      
      
